<a href="https://colab.research.google.com/github/ArnabAdhikar/GFG/blob/main/Tenserflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
## Basics of Tenserflow

In [10]:
import tensorflow as tf

In [ ]:
# initialization of tensors
x = tf.constant(10)
print(x)
y = tf.constant(20, shape=(1,1), dtype=tf.float32)
print(y)
z = tf.constant([[1,2,3],[4,5,6]], shape=(2,3))
print(z)
# Automatic initializations
a = tf.ones((3,3))
print(a)
b = tf.zeros((2,2))
print(b)
c = tf.eye(3)
print(c)
# normal distribution
d = tf.random.normal((3,3), mean = 0, stddev=1)
print(d)
# uniform distribution
e = tf.random.uniform((3,3), minval=0, maxval=1)
print(e)
f = tf.range(start=1, limit=10, delta=2)
print(f)
# conversion into specific type
f = tf.cast(f, dtype=tf.float64)
print(f)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([[20.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.25187486 -1.09488    -1.2205842 ]
 [ 0.97187275 -0.3429392  -2.0305488 ]
 [-0.06779862 -0.15545264  1.3298414 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.91279256 0.9809538  0.39092577]
 [0.35951173 0.8451289  0.71151304]
 [0.6949127  0.2904048  0.07404435]], shape=(3, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [19]:
# Mathematical operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
# adding
z = x+y
print(z)
# subtraction
z = x-y
print(z)
# multiplication
z = x*y
print(z)
# division
z = x/y
print(z)
# dot product
z = tf.tensordot(x, y, axes=1)
print(z)
# element wise exponentiation
z = x**5
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [21]:
# matrix multiply
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-1.3873882  -0.26949722 -2.798253    0.26130012]
 [-0.3659125   0.05167973 -1.3943477   0.35778937]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.3873882  -0.26949722 -2.798253    0.26130012]
 [-0.3659125   0.05167973 -1.3943477   0.35778937]], shape=(2, 4), dtype=float32)


In [29]:
# indexing a tensor
x = tf.constant([0,1,1,2,3,1,2,3])
# prints all the element
print(x[:])
# Exclude the first element
print(x[1:])
print(x[1:3])
# skipping elements
print(x[::2])
# print in reverse order
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [30]:
# gathering elements of specific indices
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [31]:
# same operations on matrix
x = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
indices = tf.constant([0,2])
x_ind = tf.gather(x, indices)
print(x_ind)
# only 1st row
print(x[0,:])
# only first 2
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [32]:
# Reshaping a tensors
x = tf.range(9)
print(x)
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [33]:
# Matrix transposition
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
